version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: ["npm", "start", "dev"]
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: