version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_USER: user
    volumes:
      - ./db:/app
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    volumes:
      - ./backend:/app
      - backend-node_modules:/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    volumes:
      - ./frontend:/app
      - frontend-node_modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  backend-node_modules:
  frontend-node_modules: